// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa0nKaF9RzW1z4an_rajNJDO-XcdOtC3M',
    appId: '1:170358377169:web:a0f304be421407205e53f0',
    messagingSenderId: '170358377169',
    projectId: 'testapp-a5eb8',
    authDomain: 'testapp-a5eb8.firebaseapp.com',
    databaseURL: 'https://testapp-a5eb8-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-a5eb8.appspot.com',
    measurementId: 'G-5G7BN686TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4tjDU7G5SF-VO9YoiiwR8Twal37tQfw',
    appId: '1:170358377169:android:dc43d1056983c4b75e53f0',
    messagingSenderId: '170358377169',
    projectId: 'testapp-a5eb8',
    databaseURL: 'https://testapp-a5eb8-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-a5eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhY8UundZpwMEEsj9cz88TCLt6QYgJow',
    appId: '1:170358377169:ios:099407c84a393d305e53f0',
    messagingSenderId: '170358377169',
    projectId: 'testapp-a5eb8',
    databaseURL: 'https://testapp-a5eb8-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-a5eb8.appspot.com',
    androidClientId: '170358377169-0e1n6eei9te2q2k6kgfhl734vmthll1t.apps.googleusercontent.com',
    iosClientId: '170358377169-7ubcbvk6spr7cfhkkndfhe5npiq9vs2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaGramRiverpod',
  );
}
